# Generated by Django 3.1.2 on 2026-02-27 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=30, null=True)),
                ("descripcion", models.TextField(max_length=100, null=True)),
                ("receta", models.CharField(max_length=1, null=True)),
                ("precio", models.FloatField(null=True)),
                ("stock", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField(null=True)),
                ("precio", models.FloatField(null=True)),
                (
                    "idPaciente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra_medicamento",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cant", models.IntegerField(null=True)),
                (
                    "idCompra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo.compra",
                    ),
                ),
                (
                    "idMedicamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo.medicamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField(null=True)),
                ("observaciones", models.TextField(max_length=200, null=True)),
                (
                    "idMedico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idPaciente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("fecha",),
            },
        ),
    ]
